### ISSUE TITLE
Make blog reactive?

### ISSUE THREAD

**Issue by da2ce7** [boken-engine/blog#1]
Here is a nice minimalist example:

https://github.com/ajboni/blog/

https://blog.aboni.dev/

**Comment by josecelano** [comment]
I think we could simplify the project if we only keep one repo with the landing page and the blog. What do you think if we remove this repo and we use Jekyll for the main site (https://github.com/boken-engine/boken-engine.github.io) with a blog?

I've found these two options:

- https://github.com/daattali/beautiful-jekyll#readme
- https://github.com/wowthemesnet/mediumish-theme-jekyll

I prefer the first one because it's simpler and that usually means easier to change although I do not like too much the "bootstrap style". But I think that style is only because of the buttons on the homepage.

**Comment by josecelano** [comment]
I've just updated the website. I think we can archive this repo.

**Comment by josecelano** [comment]
https://www.boken-engine.dev/
